dev:
  build: .
  ports:
    - 80:3000
  volumes:
    - ".:/usr/src/app"
  links:
    - pg
  environment:
    DATABASE_URL: postgres://todos:todos@pg:5432/todos

pg:
  image: postgres:10.1-alpine
  environment:
    - POSTGRES_USER=todos
    - POSTGRES_PASSWORD=todos
  volumes:
    - "./docker/psql-init:/docker-entrypoint-initdb.d"
      
